<template>
  <section>
    <h2 class="border-bottom my-4">Profile</h2>
    <p>Shaji Ahmed is a technologist with over two decades of professional experience in designing and developing computing solutions across both public and private sectors. His extensive experience equips him to offer practical guidance and advice on engineering matters.</p>
    <p>Much of his enthusiasm for civic technology originates from his profound appreciation of technology, which commenced at an early age. Growing up during the emergence of personal computers and the internet provided him with ample opportunities to explore, learn, and advance as a programmer and designer. He leveraged this experience to build websites and computer animations for clients at a relatively young age.</p>
    <p>With a history of contributing to large-scale projects throughout his career, Shaji possesses both the technical acumen and the confidence to undertake ambitious endeavors. He played a pivotal role in the development of the inaugural computerized identity cards, machine-readable passports, and driving licenses in Pakistan. Furthermore, his portfolio includes the establishment of border-control systems, online payment systems, vehicle tracking systems, and various other initiatives at the National Database and Registration Authority.</p>
    <p>Following a hiatus for academic pursuits in Malaysia, where he participated in the establishment of a virtual university, Shaji engaged in several consulting projects for the UN and other multilateral donor agencies. Notable endeavors include conducting a census of Afghan refugees in Pakistan and evaluating numerous international aid programs. In his capacity as the resident technologist, he acquired firsthand experience in data management and analysis from leading experts in the field.</p>
    <p>Shaji has spearheaded the development of innovative customer experience and engagement solutions for local telecommunications companies and governmental departments. Drawing upon his expertise in data analysis and user experience design, he steered teams toward enhancing multiple customer engagement products and processes.</p>
    <p>For the last few years, Shaji served as the Director of Engineering at AlphaX Decision Sciences where he was involved in implementing cutting-edge machine learning models and developing decision support systems for clients in Middle East and North America in the oil and energy sector.</p>
    <p>Most recently, Shaji has taken charge of Code for Pakistan, a civictech non-profit, where he works on bringing government culture change in Pakistan by partnering with the government and advising both the public and private sectors on designing technology around communities.</p>
    <p>He holds educational backgrounds in Computing and Visual Effects for Film from institutions in Pakistan and Malaysia. Shaji is based in Islamabad, Pakistan.</p>
  </section>
</template>